### ISSUE TITLE
Cannot read properties of null (reading 'job')

### ISSUE THREAD

**Issue by no-do-not-track-me** [spknetwork/video-encoder#13] opened 2022-07-02 17:38 UTC
```
10|video   | TypeError: Cannot read properties of null (reading 'job')
10|video   |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
10|video   |     at runMicrotasks (<anonymous>)
10|video   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10|video   | TypeError: Cannot read properties of null (reading 'job')
10|video   |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
10|video   |     at runMicrotasks (<anonymous>)
10|video   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10|video   | TypeError: Cannot read properties of null (reading 'job')
10|video   |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
10|video   |     at runMicrotasks (<anonymous>)
10|video   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10|video   | TypeError: Cannot read properties of null (reading 'job')
10|video   |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
10|video   |     at runMicrotasks (<anonymous>)
10|video   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10|video   | TypeError: Cannot read properties of null (reading 'job')
10|video   |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
10|video   |     at runMicrotasks (<anonymous>)
10|video   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by vaultec81** [comment] 2022-07-02 23:49
I am going to close this as a duplicate of https://github.com/spknetwork/video-encoder/issues/1

**Closed by vaultec81** 2022-07-02 23:49 UTC
